### ISSUE TITLE
Mark test class to be run wholly on one emulator?

### ISSUE THREAD

**Issue by zsperske** [shazam/fork#120]
Some of our tests need to be run serially in order to ensure correct state, is it possible to mark a test class to only run on one device?

**Comment by iordanis** [comment]
I think generally that's a bad idea. Tests should be self-contained for stability and reproducability. How about setting up the correct state as part of the individual test setup (rather than depending on a different test running before).

As far as I know, JUnit doesn't provide guarantees for test execution order.

In any case, I don't see us ever supporting this.

**Comment by zsperske** [comment]
While I certainly agree that tests should be self contained, we run some of our tests against live servers. Multiple tests running against the same server simultaneously (especially considering your point about non guaranteed execution order) can leave to unpredictable behavior.

**Comment by iordanis** [comment]
Closing this as discussed previously. I believe the best way to achieve this is with test rules.
