### ISSUE TITLE
Filter on test annotation @SmallTest, @MediumTest, @LargeTest

### ISSUE THREAD

**Issue by tmelz** [shazam/fork#23]
Spoon provides this functionality so I assumed it would be available here; am I missing something or is it not supported?

**Comment by iordanis** [comment]
You're right that we haven't added support for it, because we haven't needed it. All of our tests would classify as medium according to: http://googletesting.blogspot.co.uk/2010/12/test-sizes.html. 

I haven't seen how Spoon handles it but it is probably a relatively isolated change. Check the TestClassScanner, DexMethodAnnotationVisitor and SuppressedMethodFlagSetter classes. We already filter suppressed tests that way.
