### ISSUE TITLE
Add fine-grained control for permissions on Marshmallow devices

### ISSUE THREAD

**Issue by iordanis** [shazam/fork#75]
This will most likely need a way to control what permissions get granted per test.

**Comment by sean-kenny** [comment]
Yes. We have some tests that verify permission flows, for those tests ideally they could opt out of automated permission grants..

As an aside, it would also be nice to clear permissions between tests (not sure if that's being done or not)

**Comment by fpezzato** [comment]
This is something I wanted to add since a long time!
1) In general l am keen to keep the automatically granted permissions on every test (unless opted out with `autoGrantPermissions=false`). Only when a test is *explicitly* annotated with one or more permissions to revoke than fork should revoke them for that single test. 

2) What I am not sure about is how to annotate a test to indicate which permission(s) should be revoked before running it.
An idea could be to hijack the android support annotation `RequiresPermission` (https://developer.android.com/reference/android/support/annotation/RequiresPermission.html):
_Pro_:
That's a well established annotation, there is no need to add a new one in Fork (that would require the client application to import a new annotation...)
_Cons_: 
the semantic of the annotation would be used "inverted" (that could be misleading). So for example a test annotated with `    @RequiresPermission(allOf = {Manifest.permission.RECORD_AUDIO, Manifest.permission.CAMERA})` would be executed *without* such permissions granted.

What do you guys think?

------
@sean-kenny :
>   (not sure if that's being done or not)

So far there is no fine tuning or revoking of any permissions: we just auto-grant all permissions when installing the apk.

**Comment by fpezzato** [comment]
PR : https://github.com/shazam/fork/pull/124
